/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bmjo.hackbug.ui;

import com.bmjo.hackbug.core.CommonDataArea;

import com.bmjo.hackbug.core.MainControler;
import com.bmjo.hackbug.core.MainControler.ConEvents;
import com.bmjo.hackbug.core.MainControler.ConnectionMode;


/**
 *
 * @author bijum
 */
public class ConnectionModeView extends javax.swing.JPanel {

  /*  static String ConMode_Seraial = "SerialPort";
    static String ConMode_TCPServer = "TCPServer";
    static String ConMode_TCPClient = "TCPClient";
    public enum ConnectionModes
    {
        Serial,
        TCPServer,
        TCPClient,
    }
    public interface ConnectionModeChangeListner
    {
        public void handleConnectionModeChanged(ConnectionModes mode);
    }
    private ConnectionModes selectedMode;
    ConnectionModeChangeListner conModeChangeLisner;
     public void addConnectionModeChangeListner(ConnectionModeChangeListner lisner){
        conModeChangeLisner = lisner;
    }
    */
   
    /**
     * Creates new form ConnectionMode
     */
    public ConnectionModeView() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Connection Mode");
        jPanel1.add(jLabel1);

        add(jPanel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serial Port", "TCP Server", "TCP Client", "USB" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel2.add(jComboBox1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
     /*   if(evt.getNewValue()==MainControler.CONMODE_SERIAL){
            CommonDataArea.connectionMode = ConnectionMode.Serial;
        }else if(evt.getNewValue()==MainControler.CONMODE_TCPSERVER){
            CommonDataArea.connectionMode = ConnectionMode.TCPServer;
        }else if(evt.getNewValue()==MainControler.CONMODE_TCPCLIENT){
            CommonDataArea.connectionMode = ConnectionMode.TCPClient;
        }
        MainControler.fireConEvent(ConEvents.ConnectionModeChange, CommonDataArea.connectionMode);*/
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       String selMode = jComboBox1.getSelectedItem().toString();
          if(selMode.contains(MainControler.CONMODE_SERIAL)){
            CommonDataArea.connectionMode = ConnectionMode.Serial;
        }else if(selMode.contains(MainControler.CONMODE_TCPSERVER)){
            CommonDataArea.connectionMode = ConnectionMode.TCPServer;
        }else if(selMode.contains(MainControler.CONMODE_TCPCLIENT)){
            CommonDataArea.connectionMode = ConnectionMode.TCPClient;
        }else if(selMode.contains(MainControler.CONMODE_USB)){
            CommonDataArea.connectionMode = ConnectionMode.USB;
        }
        MainControler.fireConModeEvent(CommonDataArea.connectionMode);

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

   
}
