/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bmjo.hackbug.ui;

import com.bmjo.hackbug.core.CommonDataArea;

import com.bmjo.hackbug.serial.SerialPortConection;
import com.fazecast.jSerialComm.SerialPort;
import static javax.swing.JOptionPane.showMessageDialog;
import com.bmjo.hackbug.core.IConnection;
import com.bmjo.hackbug.core.IConnectionEvents;
import com.bmjo.hackbug.core.MainControler;
import com.bmjo.hackbug.core.MainControler.ConEvents;
import com.bmjo.hackbug.core.MainControler.ConnectionMode;

/**
 *
 * @author bijum
 */
public class SerialPortConPropView extends javax.swing.JPanel {

    ConnectionMode mode;
    
    /**
     * Creates new form SerialPortConPropSel
     */
    public SerialPortConPropView() {
        initComponents();
        FillSerialPorts();
        mode = ConnectionMode.Serial;
        MainControler.AddConEventListner(new ConnectionEventss());
    }
    
    public void FillSerialPorts()
    {
       
      SerialPort[]  ports = SerialPort.getCommPorts();
      jComboPort.removeAllItems();
     
      for(SerialPort port: ports)
      {
          String name = port.getSystemPortName();
          jComboPort.addItem(name);
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboPort = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBaudRate = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBits = new javax.swing.JComboBox<>();
        jComboParity = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();

        jLabel1.setText("Port");

        jComboPort.setName("portList"); // NOI18N

        jLabel2.setText("Baud Rate");

        jComboBaudRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "115200", "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "57600", "128000" }));
        jComboBaudRate.setName(""); // NOI18N

        jLabel3.setText("Bits");

        jComboBits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "7" }));

        jComboParity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "odd", "eve", "mark" }));

        jLabel4.setText("Parity");

        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboParity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBaudRate, 0, 96, Short.MAX_VALUE)
                            .addComponent(jComboBits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboParity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addComponent(buttonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText()=="Connect"){
           
            if(CommonDataArea.connection==null) 
            {
                CommonDataArea.connection = new SerialPortConection();
            }else {
                 CommonDataArea.connection.close();
                 CommonDataArea.connection = new SerialPortConection();
            }
            SerialPortConection.ConParams params = new SerialPortConection.ConParams();
            String baudRate = jComboBaudRate.getSelectedItem().toString();
            params.baudRate = Integer.parseInt(baudRate);
            String bits = jComboBits.getSelectedItem().toString();
            params.bits = Integer.parseInt(bits);
            params.parity = SerialPortConection.Parity.None;
            params.port = jComboPort.getSelectedItem().toString();
            if(!CommonDataArea.connection.connect(params)) {
                 showMessageDialog(this, "Connection Failed");
            }
        }else if(jButton1.getText()=="Close"){
            if(CommonDataArea.connection!=null){
                CommonDataArea.connection.close();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
          FillSerialPorts();
    }//GEN-LAST:event_buttonRefreshActionPerformed

   
    class ConnectionEventss implements IConnectionEvents{


        @Override
        public void onConnectionModeChange(ConnectionMode mode) {
            }

        @Override
        public void onEvent(MainControler.ConEvents event, Object param) {
           if(event == ConEvents.Connected){
               jButton1.setText("Close");
            }else if(event == ConEvents.ConClosed){
                 jButton1.setText("Connect");
            }        
        }

        @Override
        public void onError(MainControler.Error error, Object details) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void onReceive(byte[] data, int numBytes, IConnection eventSource, Object eventInfo) {
             return; 
        }

        @Override
        public void onSelectedConChange(IConnection connection) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBaudRate;
    private javax.swing.JComboBox<String> jComboBits;
    private javax.swing.JComboBox<String> jComboParity;
    private javax.swing.JComboBox<String> jComboPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
